games:
  - name: "valheim"
    bepinex: ["valheim", "valheim_server"]
    thunderstore: "valheim"
    nexus: "valheim"
  - name: "lethal_company"
    bepinex: ["Lethal Company"]
    thunderstore: "lethal-company"
